<a href="https://colab.research.google.com/github/porkens/myTestRepo/blob/main/Zadanie1_Bartlomiej_Noga.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import gym
import random

In [3]:
env = gym.make("Taxi-v3").env
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [4]:
action_size = env.action_space.n
print("Action size:", action_size) # Przestrzeń akcji

state_size = env.observation_space.n 
print("State size:", state_size) # Przestrzeń stanów

Action size: 6
State size: 500


In [5]:
qtable = np.zeros((state_size, action_size)) # Tworzymy tabelę Q, którą wypełniamy zerami, gdzie liczba wierszy jest równa liczbie stanów(w tym przypadku 500), a liczba kolumn jest równa liczbie akcji(6 kolumn)
print(qtable) # Tabela Q

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [6]:
total_episodes = 10000
total_test_episodes = 10
max_steps = 99

learning_rate = 0.7
gamma = 0.618

epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.01

In [7]:
for episode in range(total_episodes):
  state = env.reset()
  step = 0
  done = False

  for step in range(max_steps):
    exp_exp_tradeoff = random.uniform(0,1)

    if exp_exp_tradeoff > epsilon:
      action = np.argmax(qtable[state,:])

    else:
      action = env.action_space.sample()

    new_state, reward, done, info = env.step(action)

    qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])

    state = new_state

    if done == True:
      break
  
  episode += 1

  epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate*episode)

In [8]:
env.reset()
rewards = []

for episode in range(total_test_episodes):
  state = env.reset()
  step = 0
  done = False
  total_rewards = 0
  print("##################")
  print("   Zdarzenie:", episode)
  print("##################")

  for step in range(max_steps):
    env.render()
    action = np.argmax(qtable[state, :])

    new_state, reward, done, info = env.step(action)

    total_rewards += reward

    if done:
      rewards.append(total_rewards)
      print("Wynik:", total_rewards)
      break
    state = new_state
env.close()
print("\nŚrednia: " + str(sum(rewards)/total_test_episodes))

##################
   Zdarzenie: 0
##################
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : | : :_|
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | :_: |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
| : : :_: |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : :_: : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
| :_: : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
|_: : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | 